// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTD7fY0OVj34EqVQP0FaZm9lM_rHzU1xY',
    appId: '1:16503104818:web:93b9dabc5c3c7b3efca32b',
    messagingSenderId: '16503104818',
    projectId: 'alltestproject-1156c',
    authDomain: 'alltestproject-1156c.firebaseapp.com',
    storageBucket: 'alltestproject-1156c.appspot.com',
    measurementId: 'G-NRQBQ8RM9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKtQUDFITYBGQs-kiGlfx0xU1VhLGfy4',
    appId: '1:16503104818:android:6c9aff751a889cb4fca32b',
    messagingSenderId: '16503104818',
    projectId: 'alltestproject-1156c',
    storageBucket: 'alltestproject-1156c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1S-Hws2yl4oxgY4Qkt9Pisi5BocShGo',
    appId: '1:16503104818:ios:39291dfc70b43ccefca32b',
    messagingSenderId: '16503104818',
    projectId: 'alltestproject-1156c',
    storageBucket: 'alltestproject-1156c.appspot.com',
    iosBundleId: 'com.soda.googleAnalyticsSample',
  );
}
